#############################################################################
# Makefile for building: Alarm
# Generated by qmake (3.1) (Qt 5.15.16)
# Project:  Alarm.pro
# Template: app
# Command: /opt/homebrew/bin/qmake -o Makefile Alarm.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/macx-clang -F/opt/homebrew/Cellar/qt@5/5.15.16/lib
QMAKE         = /opt/homebrew/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/homebrew/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/homebrew/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Alarm1.0.0
DISTDIR = /Users/trinityung/group27/.tmp/Alarm1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/opt/homebrew/Cellar/qt@5/5.15.16/lib -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		clockwidget.cpp \
		mainwindow.cpp \
		setalarmwindow.cpp \
		viewAlarm.cpp \
		alarm_details.cpp moc_clockwidget.cpp \
		moc_mainwindow.cpp \
		moc_setalarmwindow.cpp \
		moc_viewAlarm.cpp \
		moc_alarm_details.cpp
OBJECTS       = main.o \
		clockwidget.o \
		mainwindow.o \
		setalarmwindow.o \
		viewAlarm.o \
		alarm_details.o \
		moc_clockwidget.o \
		moc_mainwindow.o \
		moc_setalarmwindow.o \
		moc_viewAlarm.o \
		moc_alarm_details.o
DIST          = /opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/qdevice.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_macextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_pdf.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_script.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_script_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webengine.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/warn_on.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/lex.prf \
		Alarm.pro clockwidget.h \
		mainwindow.h \
		setalarmwindow.h \
		viewAlarm.h \
		alarm_details.h main.cpp \
		clockwidget.cpp \
		mainwindow.cpp \
		setalarmwindow.cpp \
		viewAlarm.cpp \
		alarm_details.cpp
QMAKE_TARGET  = Alarm
DESTDIR       = 
TARGET        = Alarm

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 13.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/trinityung/group27/.qmake.stash
EXPORT_VALID_ARCHS = arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/trinityung/group27/Alarm.pro


include /opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Alarm:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Alarm.pro /opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/macx-clang/qmake.conf /opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/qdevice.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_macextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_pdf.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_script.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_script_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webengine.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/warn_on.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/lex.prf \
		Alarm.pro \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtGui.framework/Resources/QtGui.prl \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile Alarm.pro
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/spec_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/qdevice.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/device_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/unix.conf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/macx.conf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/sanitize.conf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/gcc-base.conf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/gcc-base-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/clang.conf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/common/clang-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/qconfig.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3danimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dcore.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_charts.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_charts_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_concurrent.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_core.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_core_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_dbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_designer.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_designer_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_gamepad.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_graphics_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_gui.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_gui_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_help.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_help_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_location.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_location_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_macextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_multimedia.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_network.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_network_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_networkauth.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_nfc.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_opengl.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_pdf.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_pdf_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_pdfwidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_positioning.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_printsupport.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_purchasing.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qml.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmltest.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3d.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_repparser.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_script.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_script_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_scripttools.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_scxml.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_sensors.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_serialbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_serialport.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_sql.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_sql_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_svg.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_svg_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_testlib.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_uitools.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webchannel.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webengine.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_websockets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webview.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_webview_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_widgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_xml.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_xml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/qt_functions.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/qt_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/macx-clang/qmake.conf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/exclusive_builds.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/sdk.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/default_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/default_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/resolve_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/objective_c.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/mac.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/warn_on.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/qt.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/resources_functions.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/resources.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/moc.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/unix/opengl.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/uic.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/unix/thread.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/qmake_use.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/file_copies.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/rez.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/mac/asset_catalogs.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/testcase_targets.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/exceptions.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/yacc.prf:
/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/lex.prf:
Alarm.pro:
/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtGui.framework/Resources/QtGui.prl:
/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Alarm.pro

qmake_all: FORCE


all: Makefile Alarm

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents clockwidget.h mainwindow.h setalarmwindow.h viewAlarm.h alarm_details.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp clockwidget.cpp mainwindow.cpp setalarmwindow.cpp viewAlarm.cpp alarm_details.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h /opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_clockwidget.cpp moc_mainwindow.cpp moc_setalarmwindow.cpp moc_viewAlarm.cpp moc_alarm_details.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_clockwidget.cpp moc_mainwindow.cpp moc_setalarmwindow.cpp moc_viewAlarm.cpp moc_alarm_details.cpp
moc_clockwidget.cpp: clockwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLCDNumber \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qdatetime.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.16/bin/moc $(DEFINES) --include /Users/trinityung/group27/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/macx-clang -I/Users/trinityung/group27 -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.16/lib clockwidget.h -o moc_clockwidget.cpp

moc_mainwindow.cpp: mainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QMessageBox \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qtimer.h \
		clockwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLCDNumber \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		setalarmwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QTimeEdit \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QComboBox \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qcombobox.h \
		viewAlarm.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QFrame \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qframe.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QScrollArea \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QFile \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTextStream \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qtextstream.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.16/bin/moc $(DEFINES) --include /Users/trinityung/group27/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/macx-clang -I/Users/trinityung/group27 -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.16/lib mainwindow.h -o moc_mainwindow.cpp

moc_setalarmwindow.cpp: setalarmwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QTimeEdit \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QComboBox \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qcombobox.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.16/bin/moc $(DEFINES) --include /Users/trinityung/group27/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/macx-clang -I/Users/trinityung/group27 -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.16/lib setalarmwindow.h -o moc_setalarmwindow.cpp

moc_viewAlarm.cpp: viewAlarm.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QFrame \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qframe.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QScrollArea \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QFile \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTextStream \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qtextstream.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.16/bin/moc $(DEFINES) --include /Users/trinityung/group27/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/macx-clang -I/Users/trinityung/group27 -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.16/lib viewAlarm.h -o moc_viewAlarm.cpp

moc_alarm_details.cpp: alarm_details.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QHBoxLayout \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.16/bin/moc $(DEFINES) --include /Users/trinityung/group27/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.16/mkspecs/macx-clang -I/Users/trinityung/group27 -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.16/lib alarm_details.h -o moc_alarm_details.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QApplication \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qapplication.h \
		mainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QMessageBox \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qtimer.h \
		clockwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLCDNumber \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		setalarmwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QTimeEdit \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QComboBox \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qcombobox.h \
		viewAlarm.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QFrame \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qframe.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QScrollArea \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QFile \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTextStream \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qtextstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

clockwidget.o: clockwidget.cpp clockwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLCDNumber \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clockwidget.o clockwidget.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QMessageBox \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qtimer.h \
		clockwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLCDNumber \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		setalarmwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QTimeEdit \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QComboBox \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qcombobox.h \
		viewAlarm.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QFrame \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qframe.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QScrollArea \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QFile \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTextStream \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qtextstream.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QDebug \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

setalarmwindow.o: setalarmwindow.cpp setalarmwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QTimeEdit \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QComboBox \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qcombobox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setalarmwindow.o setalarmwindow.cpp

viewAlarm.o: viewAlarm.cpp viewAlarm.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QFrame \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qframe.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QScrollArea \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QFile \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QTextStream \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qtextstream.h \
		alarm_details.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/QDebug \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewAlarm.o viewAlarm.cpp

alarm_details.o: alarm_details.cpp alarm_details.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Headers/QHBoxLayout
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alarm_details.o alarm_details.cpp

moc_clockwidget.o: moc_clockwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clockwidget.o moc_clockwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_setalarmwindow.o: moc_setalarmwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setalarmwindow.o moc_setalarmwindow.cpp

moc_viewAlarm.o: moc_viewAlarm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewAlarm.o moc_viewAlarm.cpp

moc_alarm_details.o: moc_alarm_details.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_alarm_details.o moc_alarm_details.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

